[tool.poetry]
name = "dora-parler"
version = "0.3.7rc0"
authors = [
    "Haixuan Xavier Tao <tao.xavier@outlook.com>",
    "Enzo Le Van <dev@enzo-le-van.fr>",
]
description = "Dora Node for Text to speech with dora Parler-TTS"
readme = "README.md"

packages = [{ include = "dora_parler" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
parler_tts = { git = "https://github.com/huggingface/parler-tts.git" }
transformers = ">=4.43.0,<=4.43.3"
torch = "^2.2.0"
torchaudio = "^2.2.2"
sentencepiece = "^0.1.99"
python = "^3.7"
pyaudio = "^0.2.14"
modelscope = "^1.18.1"


[tool.poetry.scripts]
dora-parler = "dora_parler.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
